
version: "3.9"
services:
  app:
    depends_on:
      - mongo
    restart: always
    container_name: blog-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - .docker_env
    ports:
      - "3000:3000"
    volumes:
      - ../.:/app
  
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .docker_env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: blogDB
    volumes:
      - ./mongoScript.js:/docker-entrypoint-initdb.d/mongoScript.js:ro