
version: "3.9"
services:
  app:
    depends_on:
      - mongo
    restart: always
    container_name: blog-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../.:/app
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"